# Generated by Django 4.0.1 on 2022-01-31 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appleapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenresDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'genres',
            },
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='app_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8),
        ),
        migrations.AlterModelTable(
            name='productdetails',
            table='product_details',
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='genres',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appleapp.genresdetails'),
        ),
    ]
