# Generated by Django 4.0.1 on 2022-01-31 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appleapp', '0002_genresdetails_alter_productdetails_app_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetails',
            name='genres',
        ),
    ]
